In [131]:
# Importing the required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


%matplotlib inline 

# To ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Load the dataset
df = pd.read_csv("AmesHousing.csv")

In [132]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [133]:
#Drop these 2 columns as they are surplus to requirements and not useful
df=df.drop(columns='PID')
df=df.drop(columns='Order')

In [134]:
# Check the data types of each column and tells you how many rows and columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS SubClass      2930 non-null   int64
 1   MS Zoning        2930 non-null   object
 2   Lot Frontage     2440 non-null   float64
 3   Lot Area         2930 non-null   int64
 4   Street           2930 non-null   object
 5   Alley            198 non-null    object
 6   Lot Shape        2930 non-null   object
 7   Land Contour     2930 non-null   object
 8   Utilities        2930 non-null   object
 9   Lot Config       2930 non-null   object
 10  Land Slope       2930 non-null   object
 11  Neighborhood     2930 non-null   object
 12  Condition 1      2930 non-null   object
 13  Condition 2      2930 non-null   object
 14  Bldg Type        2930 non-null   object
 15  House Style      2930 non-null   object
 16  Overall Qual     2930 non-null   int64
 17  Overall Cond     2930 non-null   int64
 18  Year Built       2930 non-null   int64
 19  Year Remod/Add   2930 non-null   int64
 20  Roof Style       2930 non-null   object
 21  Roof Matl        2930 non-null   object
 22  Exterior 1st     2930 non-null   object
 23  Exterior 2nd     2930 non-null   object
 24  Mas Vnr Type     1155 non-null   object
 25  Mas Vnr Area     2907 non-null   float64
 26  Exter Qual       2930 non-null   object
 27  Exter Cond       2930 non-null   object
 28  Foundation       2930 non-null   object
 29  Bsmt Qual        2850 non-null   object
 30  Bsmt Cond        2850 non-null   object
 31  Bsmt Exposure    2847 non-null   object
 32  BsmtFin Type 1   2850 non-null   object
 33  BsmtFin SF 1     2929 non-null   float64
 34  BsmtFin Type 2   2849 non-null   object
 35  BsmtFin SF 2     2929 non-null   float64
 36  Bsmt Unf SF      2929 non-null   float64
 37  Total Bsmt SF    2929 non-null   float64
 38  Heating          2930 non-null   object
 39  Heating QC       2930 non-null   object
 40  Central Air      2930 non-null   object
 41  Electrical       2929 non-null   object
 42  1st Flr SF       2930 non-null   int64
 43  2nd Flr SF       2930 non-null   int64
 44  Low Qual Fin SF  2930 non-null   int64
 45  Gr Liv Area      2930 non-null   int64
 46  Bsmt Full Bath   2928 non-null   float64
 47  Bsmt Half Bath   2928 non-null   float64
 48  Full Bath        2930 non-null   int64
 49  Half Bath        2930 non-null   int64
 50  Bedroom AbvGr    2930 non-null   int64
 51  Kitchen AbvGr    2930 non-null   int64
 52  Kitchen Qual     2930 non-null   object
 53  TotRms AbvGrd    2930 non-null   int64
 54  Functional       2930 non-null   object
 55  Fireplaces       2930 non-null   int64
 56  Fireplace Qu     1508 non-null   object
 57  Garage Type      2773 non-null   object
 58  Garage Yr Blt    2771 non-null   float64
 59  Garage Finish    2771 non-null   object
 60  Garage Cars      2929 non-null   float64
 61  Garage Area      2929 non-null   float64
 62  Garage Qual      2771 non-null   object
 63  Garage Cond      2771 non-null   object
 64  Paved Drive      2930 non-null   object
 65  Wood Deck SF     2930 non-null   int64
 66  Open Porch SF    2930 non-null   int64
 67  Enclosed Porch   2930 non-null   int64
 68  3Ssn Porch       2930 non-null   int64
 69  Screen Porch     2930 non-null   int64
 70  Pool Area        2930 non-null   int64
 71  Pool QC          13 non-null     object
 72  Fence            572 non-null    object
 73  Misc Feature     106 non-null    object
 74  Misc Val         2930 non-null   int64
 75  Mo Sold          2930 non-null   int64
 76  Yr Sold          2930 non-null   int64
 77  Sale Type        2930 non-null   object
 78  Sale Condition   2930 non-null   object
 79  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(26), object(43)
memory usage: 1.8+ MB

In [135]:
#print out the columns with missing values in descending order 
missing_values = df.isnull().sum()
highest_counts = missing_values.sort_values(ascending=False)
highest_counts[highest_counts>0]

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Cond        159
Garage Yr Blt      159
Garage Finish      159
Garage Qual        159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
BsmtFin Type 1      80
Bsmt Cond           80
Bsmt Qual           80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
Bsmt Unf SF          1
Garage Cars          1
Electrical           1
Total Bsmt SF        1
BsmtFin SF 1         1
Garage Area          1
BsmtFin SF 2         1
dtype: int64

In [136]:
# List of categorical columns
categorical = df.select_dtypes(include=['object']).columns

# Replace nulls with 'NA' in categorical columns
df[categorical] = df[categorical].fillna('NA')

# Optionally, you can verify the changes
print(df.head())

   MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0           20        RL         141.0     31770   Pave    NA       IR1
1           20        RH          80.0     11622   Pave    NA       Reg
2           20        RL          81.0     14267   Pave    NA       IR1
3           20        RL          93.0     11160   Pave    NA       Reg
4           60        RL          74.0     13830   Pave    NA       IR1

  Land Contour Utilities Lot Config  ... Pool Area Pool QC  Fence  \
0          Lvl    AllPub     Corner  ...         0      NA     NA
1          Lvl    AllPub     Inside  ...         0      NA  MnPrv
2          Lvl    AllPub     Corner  ...         0      NA     NA
3          Lvl    AllPub     Corner  ...         0      NA     NA
4          Lvl    AllPub     Inside  ...         0      NA  MnPrv

  Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  Sale Condition  SalePrice
0           NA        0       5     2010        WD           Normal     215000
1           NA        0       6     2010        WD           Normal     105000
2         Gar2    12500       6     2010        WD           Normal     172000
3           NA        0       4     2010        WD           Normal     244000
4           NA        0       3     2010        WD           Normal     189900

[5 rows x 80 columns]

In [137]:
# List of numeric columns
numeric = df.select_dtypes(include=['number']).columns

# Replace nulls with 0.0 in numeric columns
df[numeric] = df[numeric].fillna(0.0)

# Optionally, you can verify the changes
print(df.head())

   MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0           20        RL         141.0     31770   Pave    NA       IR1
1           20        RH          80.0     11622   Pave    NA       Reg
2           20        RL          81.0     14267   Pave    NA       IR1
3           20        RL          93.0     11160   Pave    NA       Reg
4           60        RL          74.0     13830   Pave    NA       IR1

  Land Contour Utilities Lot Config  ... Pool Area Pool QC  Fence  \
0          Lvl    AllPub     Corner  ...         0      NA     NA
1          Lvl    AllPub     Inside  ...         0      NA  MnPrv
2          Lvl    AllPub     Corner  ...         0      NA     NA
3          Lvl    AllPub     Corner  ...         0      NA     NA
4          Lvl    AllPub     Inside  ...         0      NA  MnPrv

  Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  Sale Condition  SalePrice
0           NA        0       5     2010        WD           Normal     215000
1           NA        0       6     2010        WD           Normal     105000
2         Gar2    12500       6     2010        WD           Normal     172000
3           NA        0       4     2010        WD           Normal     244000
4           NA        0       3     2010        WD           Normal     189900

[5 rows x 80 columns]

In [138]:
#Add all the baths together in the house and put into one column then delete the rest. We only care how many baths there are
bath_columns = [col for col in df.columns if 'Bath' in col]

# Check if any columns contain the word 'bath'
if not bath_columns:
    print("No columns containing the word 'bath' found.")
else:
    # Summing up the bath columns
    total_baths = df[bath_columns].sum(axis=1)

    # Storing the total in a variable called 'Total Baths'
    df['Total Baths'] = total_baths

    # Drop the original bath columns
    df.drop(columns=bath_columns, inplace=True)

    # Display the DataFrame to verify changes
    print(df.head())

   MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0           20        RL         141.0     31770   Pave    NA       IR1
1           20        RH          80.0     11622   Pave    NA       Reg
2           20        RL          81.0     14267   Pave    NA       IR1
3           20        RL          93.0     11160   Pave    NA       Reg
4           60        RL          74.0     13830   Pave    NA       IR1

  Land Contour Utilities Lot Config  ... Pool QC  Fence Misc Feature Misc Val  \
0          Lvl    AllPub     Corner  ...      NA     NA           NA        0
1          Lvl    AllPub     Inside  ...      NA  MnPrv           NA        0
2          Lvl    AllPub     Corner  ...      NA     NA         Gar2    12500
3          Lvl    AllPub     Corner  ...      NA     NA           NA        0
4          Lvl    AllPub     Inside  ...      NA  MnPrv           NA        0

  Mo Sold Yr Sold  Sale Type  Sale Condition  SalePrice  Total Baths
0       5    2010        WD           Normal     215000          2.0
1       6    2010        WD           Normal     105000          1.0
2       6    2010        WD           Normal     172000          2.0
3       4    2010        WD           Normal     244000          4.0
4       3    2010        WD           Normal     189900          3.0

[5 rows x 77 columns]

In [139]:
# Creating ' Finished Garage' column for Finished or Rough Finished garages.
#This is because it's relevant whether the garage is finished and also whether its detached when selling property (bias?)
searchfor = ['Fin', 'RFn']
df['Finished Garage'] = np.where(df['Garage Finish'].str.contains('|'.join(searchfor)), 1, 0)

# Creating 'Has Detached Garage' column
df['Detached Garage'] = np.where(df['Garage Type'].str.contains('Detchd'), 1, 0)

# Dropping unnecessary columns
df.drop(['Garage Finish', 'Garage Yr Blt', 'Garage Type'], axis=1, inplace=True)

In [140]:
#We only need "Bsmt Qual" to determine if a basement exists or not
df.drop(['BsmtFin Type 1', 'BsmtFin Type 2', 'Bsmt Cond', 'Bsmt Exposure'], axis=1, inplace=True)

In [141]:
# Create a new column 'Is Remodeled' based on 'Year Remod/Add'
df['Remodeled'] = (df['Year Remod/Add'] != df['Year Built']).astype(int)

# Drop the 'Year Remod/Add' column
df.drop(columns=['Year Remod/Add'], inplace=True)

From looking at https://jse.amstat.org/v19n3/decock/DataDocumentation.txt, I can dig out Ordinal values with scales as follows:  Ex-Gd-TA-Fa-Po-NA” scale, so I’ll define a function to convert them all to a “5–4–3–2–1–0” scale at the same time.   NA

In [142]:
def scale(df, column_list):
    for column in column_list:
        df[column] = df[column].map({'Ex':5, 'Gd':4, 'TA':3, 'Fa':2, 'Po':1, 'NA':0})
        df[column] = pd.to_numeric(df[column])
        df[column] = df[column].fillna(0)

column_list = ['Bsmt Qual', 'Exter Qual', 'Exter Cond', 'Fireplace Qu', 'Garage Qual', 'Garage Cond', 'Pool QC', 'Kitchen Qual', 'Heating QC']
scale(df, column_list)

In [143]:
# Created dummy columns

df = pd.get_dummies(df, columns = ['Lot Config', 'MS Zoning', 'Misc Feature', 
                                   'House Style', 'Bldg Type', 'Mas Vnr Type', 'Condition 1', 'Roof Style', 'Heating', 'Sale Condition', 'Street', 'Exterior 1st', 'Neighborhood'], drop_first=True, dtype=int)

In [144]:
df["Lot Shape"] = df["Lot Shape"].map({"Reg":3,"IR1":2, "IR2":1, "IR2":0}).fillna(0)
df["Utilities"] = df["Utilities"].map({"AllPub":3,"NoSewr":2, "NoSeWa":1, "ELO":0}).fillna(0)
df["Land Slope"] = df["Land Slope"].map({"Gtl":2,"Mod":1, "Sev":0}).fillna(0)
df["Electrical"] = df["Electrical"].map({"SBrkr":4, "FuseA":3,"FuseF":2, "FuseP":1, "Mix":0}).fillna(0)
df["Functional"] = df["Functional"].map({"Typ":7, "Min1":6, "Min2":5, "Mod":4, "Maj1":3,"Maj2":2, "Sev":1, "Sal":0}).fillna(0)
df["Paved Drive"] = df["Paved Drive"].map({"N":0, "P":1, "Y":2}).fillna(0)
df["Fence"] = df["Fence"].map({"GdPrv":4, "MnPrv":3,"GdWo":2, "MnWw":1, "NA":0}).fillna(0)
df["Central Air"] = df["Central Air"].map({"Y":1, "N":0}).fillna(0)
#df["Misc Feature"] = df["Misc Feature"].map({"Elev":5, "Gar2":4, "Othr":3,"Shed":2, "TenC":1, "NA":0}).fillna(0)
#df["Alley"] = df["Alley"].map({"Grvl":2,"Pave":1, "NA":0}).fillna(0)
#df["Mas Vnr Type"] = df["Mas Vnr Type"].map({"Stone":4, "BrkFace":3,"BrkCmn":2, "CBlock":1, "None":0}).fillna(0)
#df["Garage Type"] = df["Garage Type"].map({"Attchd":6, "BuitIn":5, "Basment":4, "Detchd":3,"2Types":2, "CarPort":1, "NA":0}).fillna(0)

In [145]:
#Convert Year Build into Age
import datetime
# Get the current year
current_year = datetime.datetime.now().year

# Create a new column 'Age' based on the year column
df['Age'] = current_year - df['Year Built']

# Optionally, drop the original year column
df.drop(columns=['Year Built'], inplace=True)

In [146]:
# Consolidating Alley columns into 'Has Alley'

lookfor = 'Grvl', 'Pave'

df['Has Alley'] = np.where(df['Alley'].str.contains('|'.join(lookfor)), 1, 0)


df.drop(['Alley'], axis=1, inplace=True)

In [147]:
#Drop BsmtFin SF 1,	BsmtFin SF 2, Bsmt Unf SF and keep Total Bsmt SF (its the total)
#Drop '1st Flr SF',	'2nd Flr SF', 'Low Qual Fin SF' and keep Gr Liv Area (it's the total)
 
df.drop(['BsmtFin SF 1','BsmtFin SF 2',	'Bsmt Unf SF'], axis=1, inplace=True)
df.drop(['1st Flr SF',	'2nd Flr SF', 'Low Qual Fin SF'], axis=1, inplace=True)

In [148]:
numerical = df.select_dtypes("number")
numerical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Columns: 116 entries, MS SubClass to Has Alley
dtypes: float64(8), int32(73), int64(35)
memory usage: 1.8 MB

In [150]:
#Drop Land Contour, Roof Matl
#Drop Condition 2, Exterior 2nd, Foundation as not important (possible bias from me)
df.drop(['Land Contour', 'Condition 2', 'Roof Matl', 'Foundation', 'Sale Type', 'Exterior 2nd'], axis=1, inplace=True)

In [151]:
# Now examine the strings
string = df.select_dtypes(object)
string.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Neighborhood  2930 non-null   object
dtypes: object(1)
memory usage: 23.0+ KB

In [152]:
df.to_csv('df.csv', index=False) #output to df.csv to help me analyse